global:
  env: dev
  valuesFile: values.yaml
  server: https://kubernetes.default.svc
  repoURL: 'https://github.com/tainguyen2604/test-argocd.git'
  repoBranch: 'main'

argocdApplications:
  metric-server:
    UseCustomName:
      enable: false
      name: "prometheus-dev"
    RepoName: metrics-server
    RepoURL: 'https://charts.bitnami.com/bitnami'
    name: metrics-server
    namespace: prometheus-test
    ChartName: "metrics-server"
    ChartVersion: 6.2.1
  prometheus:
    UseCustomName:
      enable: true
      name: "prometheus-dev"
    RepoName: prometheus-community
    RepoURL: 'https://prometheus-community.github.io/helm-charts'
    name: prometheus
    namespace: urbox-system
    ChartName: "prometheus"
    ChartVersion: 15.10.2
  
