apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: test-gitops-cicd
  labels:
    app: github-runner
spec:
  replicas: 3
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: github-runner
        image: tainguyen2604/github-runner-og:v6
        env:
        - name: DOCKER_HOST
          value: tcp://dind.docker-in-docker:2376
        - name: GITHUB_OWNER
          value: urbox-vn
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: PAT
