replicaCount: 1

image:
  repository: quay.io/prometheus/alertmanager
  pullPolicy: IfNotPresent
  tag: "v0.24.0"

extraArgs: {}


service:
  annotations: {}
  type: ClusterIP
  port: 9093
  clusterPort: 9094
  loadBalancerIP: ""  # Assign ext IP when Service type is LoadBalancer
  loadBalancerSourceRanges: []  # Only allow access to loadBalancerIP from these IPs
  # if you want to force a specific nodePort. Must be use with service.type=NodePort
  # nodePort:


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 10m
  #   memory: 32Mi

nodeSelector: {}

tolerations: []


command: []

persistence:
  enabled: false

config:
  global:
    resolve_timeout: 1m
  templates:
    - '/etc/alertmanager/*.tmpl'

  receivers:
    - name: devops-team
      telegram_configs:
      - api_url: "https://api.telegram.org"
        send_resolved: true
        parse_mode: "HTML"
        bot_token: 5605868669:AAFj3qPXIXDOJHtI_z8DbdEbnJLN2Z4zs1E
        chat_id: 1452658812
        message: '{{ template "telegram.urbox" . }}'
        
  route:
    # default receiver
    receiver: devops-team
    # tag to group by
    group_by: ['alertname', 'cluster', 'service_type']
    # How long to initially wait to send a notification for a group of alerts
    group_wait: 30s
    # How long to wait before sending a notification about new alerts that are added to a group
    group_interval: 10s
    # How long to wait before sending a notification again if it has already been sent successfully for an alert
    repeat_interval: 1m
#     routes:
#     - match:
#         severity: critical
#       receiver: system-team
#     - match:
#         severity: warning
#       receiver: system-team-warning
  #templates: ['/config/*.tmpl']
configmapReload:
  enabled: false
  name: configmap-reload

  image:
    repository: jimmidyson/configmap-reload
    tag: v0.5.0
    pullPolicy: IfNotPresent


templates:
    telegram.tmpl: |-
      {{ define "telegram.urbox" }}
      {{ range $i, $alert :=.Alerts }}
      🚀<b>========Urbox-Alert==========</b>
      {{if eq .Status "firing"}}
      Status: <b>{{.Status | toUpper }} 🔥</b>
      {{else}}
      Status: <b>{{.Status | toUpper }} ✅</b>
      {{- end -}}
      {{- if eq $alert.Labels.severity "warning"}}
      <b>Severity:</b>: ⚠️⚠️⚠️ {{ $alert.Labels.severity | toUpper }}
      {{else}}
      <b>Severity:</b> <b>⛔️⛔️⛔️ {{ $alert.Labels.severity | toUpper }}</b>
      {{- end}}
      <b>AlertName</b>： "<span style=\"color:red;\">{{ $alert.Labels.alertname }}</span>"
      <b>Descriptions</b>：{{ $alert.Annotations.description }}
      <b>Summary</b>：{{ $alert.Annotations.summary }}
      <b>ActiveAt</b> ⏱ ：{{ ($alert.StartsAt.Add 25200e9 ).Format "2006-01-02 15:04:05" }} ⏱
      =============END============🔚

      {{- end -}}
      {{- end -}} 
