apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "urbox-charts.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
  annotations:
    {{- if .Values.secret.fromVault }}
    avp.kubernetes.io/path: {{ .Values.secret.VaultPath }}
    {{- end }}
type: {{ default "Opaque" .Values.secret.type }}
stringData:
  {{- range $key, $value := .Values.secret.stringData }}
  {{ $key }}: {{ $value }}
  {{- end }}