apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  configManagementPlugins: |
    - name: helm-resolver
      init:
        command: [bash, -c]
        args: ["helm repo add ${ARGOCD_ENV_REPO_NAME} ${ARGOCD_ENV_REPO_URL} && helm repo update"]
      generate:
        command: [bash, -c]
        args: ["helm template  --include-crds -n ${ARGOCD_APP_NAMESPACE} ${ARGOCD_ENV_COMMAND} ${ARGOCD_APP_NAME} ${ARGOCD_ENV_REPO_NAME}/${ARGOCD_ENV_CHART_NAME} --version ${ARGOCD_ENV_CHART_VERSION}"]