apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: jaeger
    server: 'https://kubernetes.default.svc'
  source:
    path: values
    repoURL: 'https://github.com/tainguyen2604/test-argocd.git'
    targetRevision: HEAD
    plugin:
      name: helm-resolver
      env:
        - name: REPO_NAME
          value: elastic
        - name: REPO_URL
          value: 'https://helm.elastic.co'
        - name: CHART_NAME
          value: elasticsearch
        - name: COMMAND
          value: '--values elasticsearch.yml'
        - name: CHART_VERSION
          value: 7.17.3
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 2
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 1m0s
