apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: jaeger
    server: 'https://kubernetes.default.svc'
  source:
    path: values
    repoURL: 'https://github.com/tainguyen2604/test-argocd.git'
    targetRevision: HEAD
    plugin:
      name: helm-resolver
      env:
        - name: REPO_NAME
          value: jaegertracing
        - name: REPO_URL
          value: 'https://jaegertracing.github.io/helm-charts'
        - name: CHART_NAME
          value: jaeger
        - name: COMMAND
          value: '--values jaeger.yml'
        - name: CHART_VERSION
          value: 0.62.1
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 3
      backoff:
        duration: 1m
        factor: 1
        maxDuration: 2m
