apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind
  namespace: test-gitops-cicd
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 20Gi
