apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: urbox-system
    server: 'https://3BB5B54B3C9FD99C2B2527906D78A1E0.gr7.ap-southeast-1.eks.amazonaws.com'
  source:
    path: apps/manifest/dev/values
    repoURL: 'git@github.com:urbox-vn/gitops-application-k8s.git'
    targetRevision: main
    plugin:
      name: helm-resolver
      env:
        - name: REPO_NAME
          value: prometheus-community
        - name: REPO_URL
          value: 'https://prometheus-community.github.io/helm-charts'
        - name: CHART_NAME
          value: prometheus
        - name: COMMAND
          value: '--values prometheus-values.yml'
        - name: CHART_VERSION
          value: 15.10.2
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
