apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cm-prometheus
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    path: addons/configmap/prometheus
    repoURL: 'https://github.com/tainguyen2604/test-argocd.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true