apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
spec:
  generators:
#   - list:
#       elements:
#       - cluster: eks-production
#         url: https://kubernetes.default.svc
# #       - cluster: eks-dev
# #         url: https://3BB5B54B3C9FD99C2B2527906D78A1E0.gr7.ap-southeast-1.eks.amazonaws.com
  - git:
      repoURL: https://github.com/tainguyen2604/test-argocd
      revision: main
      directories:
        # - path: apps/manifest/production/values
        - path: values/*
  template:
    metadata:
      name: '{{cluster}}-prometheus'
    spec:
      project: default
      source:
        path: {{path}}
        repoURL: 'https://github.com/urbox-vn/gitops-application-k8s.git'
        targetRevision: main
        plugin:
          name: helm-resolver
          env:
            - name: REPO_NAME
              value: prometheus-community
            - name: REPO_URL
              value: 'https://prometheus-community.github.io/helm-charts'
            - name: CHART_NAME
              value: prometheus
            - name: COMMAND
              value: '--values prometheus.yml'
            - name: CHART_VERSION
              value: 15.10.2
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: monitoring
