apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
spec:
  generators:
  - git:
      repoURL: https://github.com/tainguyen2604/test-argocd
      revision: main
      directories:
        - path: applications-set/values/*
  template:
    metadata:
      name: 'prometheus'
    spec:
      project: default
      source:
        path: {{path}}
        repoURL: 'https://github.com/tainguyen2604/test-argocd'
        targetRevision: main
        plugin:
          name: helm-resolver
          env:
            - name: REPO_NAME
              value: prometheus-community
            - name: REPO_URL
              value: 'https://prometheus-community.github.io/helm-charts'
            - name: CHART_NAME
              value: prometheus
            - name: COMMAND
              value: '--values prometheus.yml'
            - name: CHART_VERSION
              value: 15.10.2
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: monitoring
