apiVersion: v1
data:
  alert-custom.yaml: |-
    groups:
      - name: Host out of disk space
        rules:
          - alert: HostOutOfDiskSpace
            expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: Host out of disk space (instance {{ $labels.instance }})
              description: "Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - name: Host high CPU load
        rules:
          - alert: HostHighCpuLoad
            expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
            for: 0m
            labels:
              severity: critical
            annotations:
              summary: Host high CPU load (instance {{ $labels.instance }}) 
              description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - name: Node Down
        rules:
          - alert: NodeDown
            expr: kube_node_status_condition{job="kubernetes-service-endpoints",condition="Ready",status="true"} == 0
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: Node Down (instance {{ $labels.instance }})
              description: "Node Down"
      - name: Pod NotReady
        rules:
          - alert: PodNotReady
            expr: sum by (namespace, pod) (max by(namespace, pod) (kube_pod_status_phase{job="kubernetes-service-endpoints", phase=~"Pending|Unknown"}) * on(namespace, pod) group_left(owner_kind) max by(namespace, pod, owner_kind) (kube_pod_owner{owner_kind!="Job"})) > 0
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: PodNotReady (pod {{ $labels.pod }})
              description: "pod Down"
      - name: Pod Restart
        rules:
          - alert: PodRestart
            expr: sum(increase(kube_pod_container_status_restarts_total{}[2m]))by(namespace,pod)>0
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: Pod Restart (pod {{ $labels.pod }})
              description: "pod Restart"
      - name: PodCrashLooping
        rules:
          - alert: PodCrashLooping
            expr: rate(kube_pod_container_status_restarts_total{job="kubernetes-service-endpoints"}[15m]) * 60 * 5 > 0
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: "<b>PodCrashLooping</b>\n - <b>Pod</b> : {{ $labels.pod }}\n - <b>Namespace</b> : {{ $labels.namespace }}"
              description: "PodCrashLooping"
      - name: PersistentVolumeErrors
        rules:
          - alert: PersistentVolumeErrors
            expr: kube_persistentvolume_status_phase{phase=~"Failed|Pending",job="kubernetes-service-endpoints"} > 0
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: PersistentVolumeErrors (pod {{ $labels.pod }})
              description: "PersistentVolumeErrors"
      - name: HostNetworkReceiveErrors
        rules:
          - alert: HostNetworkReceiveErrors
            expr: rate(node_network_receive_errs_total[2m]) / rate(node_network_receive_packets_total[2m]) > 0.01
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: Host Network Receive Errors (instance {{ $labels.instance }})
              description: "Host {{ $labels.instance }} interface {{ $labels.device }} has encountered {{ printf \"%.0f\" $value }} receive errors in the last two minutes.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - name: Node Down EC2 PRODUCTION
        rules:
          - alert: NodeDownEc2Pro
            expr: up{job="ec2_production"} == 0
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: "Node Down\n Instance {{ $labels.ec2_node }}"
              description: "Node Down"
kind: ConfigMap
metadata:
  name: prometheus-rule
  namespace: monitoring
