apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/manifest/root/production
    repoURL: 'https://github.com/tainguyen2604/test-argocd.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true