---
# Source: urbox-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name
  labels:
    helm.sh/chart: urbox-chart-0.1.0
    app.kubernetes.io/name: release-name
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: urbox-chart
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: grpc
  selector:
    app: release-name
---
# Source: urbox-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name
  labels:
    helm.sh/chart: urbox-chart-0.1.0
    app.kubernetes.io/name: release-name
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: urbox-chart
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: release-name
  template:
    metadata:
      labels:
        app: release-name
    spec:
      containers:
        - name: release-name
          image: "tainguyen2604/tool-test:v1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 9090
              protocol: TCP
          env:
            - name: abc
              value: "abc"
            - name: test
              value: "test"
          envFrom:
            - secretRef:
                name: test-secret-1
            - secretRef:
                name: test-secret-2
            - configMapRef:
                name: test-cm-1
          volumeMounts:
          - mountPath: /etc/secret-volume
            name:  secret-volume
            subPath: test.yml
          - mountPath: /etc/secret-volume
            name:  cm-volume
            subPath: test.yml
          - mountPath: /home/db
            name:  cm-volume-new
            subPath: test-new.yml
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep
                  - '10'
      volumes:
        - name: secret-volume
          secret:
            secretName: secret-volume
        - name: cm-volume
          configMap:
            name: cm-volume
        - name: cm-volume-new
          configMap:
            name: cm-volume-new
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
---
# Source: urbox-chart/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name
  labels:
    helm.sh/chart: urbox-chart-0.1.0
    app.kubernetes.io/name: release-name
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: urbox-chart
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ingressClassName: nginx
  rules:
  - host: chart-example.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: release-name
            port:
              number: 80
  - host: char1t-example.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ozkahjs1msdhj
            port:
              number: 80
      - path: /api/a
        pathType: Prefix
        backend:
          service:
            name: test1
            port:
              number: 80
---
# Source: urbox-chart/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-urbox-chart-test-connection"
  labels:
    helm.sh/chart: urbox-chart-0.1.0
    app.kubernetes.io/name: release-name
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: urbox-chart
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['release-name-urbox-chart:']
  restartPolicy: Never
