---
# Source: urbox-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: abc
  labels:
    helm.sh/chart: urbox-chart-0.1.0
    app.kubernetes.io/name: abc
    app.kubernetes.io/instance: abc
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: urbox-chart
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: abc
---
# Source: urbox-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc
  labels:
    helm.sh/chart: urbox-chart-0.1.0
    app.kubernetes.io/name: abc
    app.kubernetes.io/instance: abc
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: urbox-chart
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abc
  template:
    metadata:
      labels:
        app: abc
    spec:
      containers:
        - name: abc
          image: "nginx:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: abc
              value: "999"
            - name: test
              value: "123"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep
                  - '10'
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
---
# Source: urbox-chart/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abc
  labels:
    helm.sh/chart: urbox-chart-0.1.0
    app.kubernetes.io/name: abc
    app.kubernetes.io/instance: abc
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: urbox-chart
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ingressClassName: internal-nginx
  rules:
  - host: test-tools.urbox.services
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: abc
            port:
              number: 80
---
# Source: urbox-chart/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "abc-urbox-chart-test-connection"
  labels:
    helm.sh/chart: urbox-chart-0.1.0
    app.kubernetes.io/name: abc
    app.kubernetes.io/instance: abc
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: urbox-chart
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['abc-urbox-chart:']
  restartPolicy: Never
